### PR TITLE
Lint Markdown files, fix headings style

### LINKED ISSUE #89: A string is not translatable in `develop/items/potions.md`
The string "**Registering Potions Using an `Ingredient`**"
in [`develop/items/potions.md#L66`][file] is not localizable in Crowdin.

[file]: <https://github.com/FabricMC/fabric-docs/blob/fb7b8ac6e81099a38269672927ccb551ec7e2adc/develop/items/potions.md?plain=1#L66>

### PR DESCRIPTION
**Pull request by its-miroma**
## Linting

- Remove trailing whitespace
- Single newline at the end of each file
- Remove unnecessary quotes in frontmatters
- Use relative link for [CONTRIBUTING.md]
- Update [sidebar_translations.json]
- Increment headings one level at a time
- Remove punctuation from headings, except exclamation marks

## Headings

- Use Title Case through <https://www.titlecase.com/>
- Questions are exempted

## Other

- Capitalize various instances of "Java", "Loader", "Loom"
- Add custom heading link in [codecs.md]
- Avoid using emphasis for headings in [effects.md]
  - Side Effect: the auto-generated TOC now shows those two headings
- Change info box in [potions.md] (may fix #89)
- Add alt text to image in [hud.md]
- Avoid using invisible spaces for a line break in [creating-particles.md]
- Capitalize alt texts in [custom.md]

[CONTRIBUTING.md]: </CONTRIBUTING.md>
[sidebar_translations.json]: </sidebar_translations.json>
[codecs.md]: </develop/codecs.md#mapcodec>
[effects.md]: </develop/entities/effects.md>
[potions.md]: </develop/items/potions.md>
[hud.md]: </develop/rendering/hud.md>
[creating-particles.md]: </develop/rendering/particles/creating-particles.md>
[custom.md]: </develop/sounds/custom.md>

### CODE REVIEW

**Comment by IMB11** [comment]
Maybe it's worth integrating a markdown lint action/tool - I didn't originally suggest one because to be frank they all suck. There isn't really any good linters out there that:

- Automatic fix markdown issues using a CLI command.
- Aren't annoying to configure and understand lint errors.

**Comment by its-miroma** [comment]
I personally use [markdownlint by David Anson], which has a [VS Code extension]
and a cli.

It works pretty well and supports custom rules; there probably are some for
Title Case as well.

Its rules are pretty strict, I'd recommend disabling [MD025] and [MD026]
(with `punctuation: ".,;:。，；："`).

[markdownlint by David Anson]: <https://github.com/DavidAnson/markdownlint>
[VS Code extension]: <https://github.com/DavidAnson/vscode-markdownlint>
[MD025]: <https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md025.md>
[MD026]: <https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md026.md>

**Comment by its-miroma** [comment]
There even is a [GitHub Action], although I have to admit I'm not super
familiar with that

[GitHub Action]: <https://github.com/marketplace/actions/markdownlint-cli2-action>

**Comment by its-miroma** [comment]
> I personally use [markdownlint by David Anson](https://github.com/DavidAnson/markdownlint), which has a [VS Code extension](https://github.com/DavidAnson/vscode-markdownlint) and a cli.

> There even is a [GitHub Action](https://github.com/marketplace/actions/markdownlint-cli2-action), although I have to admit I'm not super familiar with that

Please review #101

**Review by modmuss50 — DISMISSED** [review]

**Review by IMB11 — APPROVED** [review]

**Pull request merged**
