### PR TITLE
Path needs to be recipes instead of recipe

### PR DESCRIPTION
**Pull request by Bedlessdeus**
Updated path to be the correct one, or else, the game wont load said recipe

### CODE REVIEW

**Comment by Juuxel** [comment]
The directory name is singular in MC 1.21, so the docs are correct.

**Comment by Bedlessdeus** [comment]
Could a note be added for the versions under 1.20 that require this to be plural?

**Comment by Linguardium** [comment]
> Could a note be added for the versions under 1.20 that require this to be plural?

click the version dropdown and choose 1.20.4

**Comment by Bedlessdeus** [comment]
Didn't see that before, sorry!

**Pull request closed without merging**
