### PR TITLE
Fix contribution guidelines link to 404

### PR DESCRIPTION
**Pull request by kevinthegreat1**
Self explanatory.

### CODE REVIEW

**Review by its-miroma — COMMENTED** [review]
This link shouldn't be broken, where did it not work?

https://docs.fabricmc.net/contributing#use-relative-links

**Comment by kevinthegreat1** [comment]
> This link shouldn't be broken, where did it not work?
> 
> https://docs.fabricmc.net/contributing#use-relative-links

The github homepage. <https://github.com/FabricMC/fabric-docs>  
It's also broken in <https://github.com/FabricMC/fabric-docs/blob/main/README.md>

**Comment by its-miroma** [comment]
None of the links work in GitHub...

cc. @IMB11

**Comment by IMB11** [comment]
need linting to be excluded for contributing file then

**Comment by its-miroma** [comment]
Readme is already excluded. All clear!

**Review by its-miroma — APPROVED** [review]

**Pull request merged**
