### PR TITLE
Use different `ThemeConfig` for each locale

### LINKED ISSUE #95: Localized versions of the `Contributing` page are not available
The language switch dropdown menu does not work in the following page:
<https://docs.fabricmc.net/contributing>

Not even the direct URLs show the localized content:
<https://docs.fabricmc.net/it_it/contributing>

### PR DESCRIPTION
**Pull request by its-miroma**
Fix #95

- Generate a `ThemeConfig` for each locale
- Move `CONTRIBUTING.md` to `contributing.md` to avoid rewriting
- Use relative links for `contributing` files

- [x] Move `CONTRIBUTING` files in `translated/**/`
- [x] Refactor some code
- [x] Check if types are correct
- [x] ~~Does it work with versioning?~~ Wait for `vitepress-versioning-plugin` release

### CODE REVIEW

**Comment by its-miroma** [comment]
The preview doesn't currently work for other languages because their files still use absolute links.

**Update**: it fixes the top bar, but not the pages

**Comment by its-miroma** [comment]
I asked for help over at [Vitepress](<https://github.com/vuejs/vitepress/discussions/3922>), and they told me that we were doing it wrong.

I have fixed it now, but there is some refactoring I would like to do. I do not have time for that right now, I'll see when I can do it.

I also don't know what I should do with the `CONTRIBUTING.md` files in `translated/`; I moved them to the lowercase version in a separate commit, if that's correct, otherwise I'll drop it.

**Comment by its-miroma** [comment]
Some people on Crowdin have started using absolute language links to fix the problem on their end. Again, should I modify their files here on GitHub? Can I touch `translated/`?

https://github.com/FabricMC/fabric-docs/blob/39cad1fa0f7d1f64701f0595d3d4f71ea783f494/translated/ru_ru/index.md?plain=1#L26

<sub>(PS: I do not speak Russian)</sub>

**Comment by IMB11** [comment]
> Some people on Crowdin have started using absolute language links to fix the problem on their end. Again, should I modify their files here on GitHub? Can I touch translated/?

We really need to find a way to convey the contributing guidelines to users on Crowdin, as there's no way to do this other than make the contributor process invite-only.

**Comment by IMB11** [comment]
I dont think this implementation will work with versioning, please test it out if you can.

**Comment by RushanM** [comment]
Does this mean that we need to stop using absolute links now?

**Comment by IMB11** [comment]
> Does this mean that we need to stop using absolute links now?

You should have always been using relative links in translations.

**Comment by its-miroma** [comment]
> I dont think this implementation will work with versioning, please test it out if you can.

It didn't. ~~<https://github.com/IMB11/vitepress-versioning-plugin/pull/4>~~ ~~**Update**: waiting for release~~ **Update**: Released

**Comment by IMB11** [comment]
Will publish a version for you now.

**Comment by IMB11** [comment]
0.11.0 is out, update when you can :+1:

**Comment by IMB11** [comment]
Actually i'll do it now when adding support for nav translations

**Comment by IMB11** [comment]
I think we should merge this without the localisation of the version switcher for now, it can come at a later date.

**Review by IMB11 — DISMISSED** [review]

**Comment by IMB11** [comment]
LGTM @modmuss50

**Review by modmuss50 — DISMISSED** [review]

**Review by IMB11 — DISMISSED** [review]

**Review by IMB11 — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
